# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objetivo',
            old_name='domino',
            new_name='dominio',
        ),
    ]
