# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='numero',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='dominio',
            name='numero',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='numero',
            field=models.CharField(default='', max_length=30),
        ),
    ]
