# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 22:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificacion', '0002_auto_20160920_1006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certifiacion',
            new_name='Certificacion',
        ),
        migrations.RenameField(
            model_name='dominio',
            old_name='certifiacion',
            new_name='Certificacion',
        ),
    ]
