# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificacion', '0004_m1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='M2',
        ),
    ]
