# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificacion', '0006_auto_20161004_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abc',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='M1',
        ),
        migrations.DeleteModel(
            name='Abc',
        ),
    ]
