# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificacion', '0007_auto_20161004_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificacion',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='certificacion',
            name='object_id',
        ),
    ]
