# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificacion', '0008_auto_20161004_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificacion.Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificacion.Grupo')),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificacion.Master'),
        ),
    ]
