# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificacion', '0011_auto_20161004_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=120, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='father',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='master',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='father',
        ),
        migrations.AlterField(
            model_name='control',
            name='nombre',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='numero',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='dominio',
            name='nombre',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='dominio',
            name='numero',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='nombre',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='numero',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Grupo',
        ),
        migrations.DeleteModel(
            name='Master',
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
        migrations.AddField(
            model_name='control',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificacion.Tipo'),
        ),
    ]
