# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificacion', '0012_auto_20161006_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='tipo',
        ),
        migrations.AddField(
            model_name='certificacion',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificacion.Tipo'),
        ),
    ]
