# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificacion', '0013_auto_20161006_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificacion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificacion.Tipo'),
        ),
    ]
