# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificacion', '0014_auto_20161006_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificacion',
            name='preparacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificacion.Certificacion'),
        ),
        migrations.AlterField(
            model_name='certificacion',
            name='nombre',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
