# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cumplimiento', models.BooleanField(default=False)),
                ('comentario', models.CharField(blank=True, max_length=1000)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificacion.Control')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizacion', models.DateTimeField(auto_now=True)),
                ('certificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificacion.Certificacion')),
            ],
        ),
        migrations.AddField(
            model_name='calificacion',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.Evaluacion'),
        ),
    ]
