# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0003_auto_20161009_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='cumplimiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evaluacion.Cumplimiento'),
        ),
    ]
