# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0002_auto_20161006_1406'),
        ('muro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='preparacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preparacion', to='evaluacion.Evaluacion'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='evaluacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion', to='evaluacion.Evaluacion'),
        ),
    ]
