# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 21:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muro', '0002_auto_20161002_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_auditor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='evaluacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluacion.Evaluacion'),
        ),
    ]
