# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muro', '0003_auto_20161002_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.Evaluacion'),
        ),
    ]
