# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='titulo',
        ),
        migrations.AddField(
            model_name='perfil',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Tipo'),
        ),
    ]
