# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20160920_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='algo',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
