# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_perfil_algo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='algo',
        ),
    ]
